/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.NOIvedem;
import Controller.NOIvengay;
import Controller.NOIvethang;
import static java.lang.Boolean.FALSE;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import modal.VeDem;
import modal.VeNgay;
import modal.VeThang;
import org.apache.commons.lang.StringUtils;

/**
 *
 * @author Admin
 */
public class QuanLiXe extends javax.swing.JFrame {

    /**
     * Creates new form QuanLiXe
     */
    Connection conn;
    NOIvengay noiVeNgay = new NOIvengay();
    NOIvedem noiVeDem = new NOIvedem();
    NOIvethang noiVeThang = new NOIvethang();
    public QuanLiXe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nhapMaVeNgay = new javax.swing.JTextField();
        nhapMaXeNgay = new javax.swing.JTextField();
        luuVeNgay = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        LoaiXe = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        GiaVe = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nhapMaVeDem = new javax.swing.JTextField();
        nhapMaXeDem = new javax.swing.JTextField();
        luuVeDem = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        LoaiXe2 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        GiaVe2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nhapMaVeThang = new javax.swing.JTextField();
        nhapMaXeThang = new javax.swing.JTextField();
        LoaiXe3 = new javax.swing.JComboBox<>();
        luuVeThang = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        GiaVe3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        thoiHan = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nhapHoTen = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nhapMaVeRa = new javax.swing.JTextField();
        kiemTraVeRa = new javax.swing.JButton();
        nutDoanhThu = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("QUẢN LÍ VÉ");

        jLabel2.setText("Mã vé");

        jLabel3.setText("Mã xe ");

        jLabel4.setText("Loại xe");

        nhapMaVeNgay.setText("VN");
        nhapMaVeNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapMaVeNgayActionPerformed(evt);
            }
        });

        nhapMaXeNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapMaXeNgayActionPerformed(evt);
            }
        });

        luuVeNgay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        luuVeNgay.setText("LƯU");
        luuVeNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuVeNgayActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton2.setText("thông tin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        LoaiXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe đạp", "Xe máy" }));
        LoaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoaiXeActionPerformed(evt);
            }
        });

        jLabel15.setText("Giá vé");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("VÉ NGÀY");

        GiaVe.setText("3.000 VND/ngày");

        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nhapMaVeNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GiaVe))
                            .addComponent(nhapMaXeNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(luuVeNgay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nhapMaVeNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nhapMaXeNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel4)
                    .addComponent(GiaVe))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luuVeNgay)
                    .addComponent(jButton2)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vé Ngày ", jPanel1);

        jLabel5.setText("Mã vé");

        jLabel6.setText("Mã xe");

        jLabel7.setText("Loại xe");

        jLabel8.setText("Giá vé");

        nhapMaVeDem.setText("VD");
        nhapMaVeDem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapMaVeDemActionPerformed(evt);
            }
        });

        luuVeDem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        luuVeDem.setText("LƯU");
        luuVeDem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuVeDemActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton4.setText("Thông tin");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        LoaiXe2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe đạp", "Xe máy" }));
        LoaiXe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoaiXe2ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("VÉ ĐÊM");

        GiaVe2.setText("7.000 VND/đêm");

        jLabel17.setText("Lưu ý:  vé đêm áp dụng đến 8h sáng hôm sau");

        jLabel18.setText(" Nếu sinh viên không lấy xe đúng hạn sẽ phải tính thêm tiền");

        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nhapMaXeDem, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nhapMaVeDem, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(LoaiXe2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GiaVe2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(luuVeDem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nhapMaVeDem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nhapMaXeDem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LoaiXe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(GiaVe2))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luuVeDem)
                    .addComponent(jButton4)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vé Đêm", jPanel2);

        jLabel9.setText("Mã vé");

        jLabel10.setText("Mã xe");

        jLabel11.setText("Loại xe");

        jLabel13.setText("Thời hạn");

        jLabel14.setText("Giá vé");

        nhapMaVeThang.setText("VT");

        nhapMaXeThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapMaXeThangActionPerformed(evt);
            }
        });

        LoaiXe3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe đạp", "Xe máy" }));
        LoaiXe3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoaiXe3ActionPerformed(evt);
            }
        });

        luuVeThang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        luuVeThang.setText("ĐĂNG KÝ");
        luuVeThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuVeThangActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton6.setText("THÔNG TIN");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        GiaVe3.setText("70.000 VND");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("VÉ THÁNG");

        thoiHan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        thoiHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoiHanActionPerformed(evt);
            }
        });

        jLabel23.setText("Tháng");

        jLabel12.setText("Họ Tên");

        jButton7.setText("CLEAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(LoaiXe3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thoiHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nhapMaXeThang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nhapMaVeThang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nhapHoTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 2, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(GiaVe3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(luuVeThang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(nhapHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nhapMaVeThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nhapMaXeThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(LoaiXe3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(thoiHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GiaVe3))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luuVeThang)
                    .addComponent(jButton6)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vé Tháng", jPanel3);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("XE RA");

        jLabel16.setText("Mã vé");

        kiemTraVeRa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        kiemTraVeRa.setText("Kiểm Tra");
        kiemTraVeRa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiemTraVeRaActionPerformed(evt);
            }
        });

        nutDoanhThu.setText("DOANH THU");
        nutDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutDoanhThuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16)
                .addGap(28, 28, 28)
                .addComponent(nhapMaVeRa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kiemTraVeRa)
                .addGap(86, 86, 86))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nutDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(nhapMaVeRa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(kiemTraVeRa)
                .addGap(27, 27, 27)
                .addComponent(nutDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("View");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nhapMaVeNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapMaVeNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhapMaVeNgayActionPerformed

    private void nhapMaXeNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapMaXeNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhapMaXeNgayActionPerformed

    private void LoaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoaiXeActionPerformed
        // TODO add your handling code here:
        if(LoaiXe.getSelectedItem().equals("Xe đạp")){
            GiaVe.setText("3.000 VND/ngày");
        }
        else if(LoaiXe.getSelectedItem().equals("Xe máy")){
            GiaVe.setText("5.000 VND/ngày");
        }
        
    }//GEN-LAST:event_LoaiXeActionPerformed

    private void LoaiXe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoaiXe2ActionPerformed
        // TODO add your handling code here:
        if(LoaiXe2.getSelectedItem().equals("Xe đạp")){
            GiaVe2.setText("7.000 VND/đêm");
        }
        else if(LoaiXe2.getSelectedItem().equals("Xe máy")){
            GiaVe2.setText("10.000 VND/đêm");
        }
    }//GEN-LAST:event_LoaiXe2ActionPerformed

    private void LoaiXe3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoaiXe3ActionPerformed
        // TODO add your handling code here:
        if(LoaiXe3.getSelectedItem().equals("Xe đạp")){
            GiaVe3.setText("70.000 VND");
        }
        else if(LoaiXe3.getSelectedItem().equals("Xe máy")){
            GiaVe3.setText("100.000 VND");
        }
    }//GEN-LAST:event_LoaiXe3ActionPerformed


    private void luuVeThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuVeThangActionPerformed
        // TODO add your handling code here:
        VeThang vthang  = new VeThang();
        vthang.setHoTen(nhapHoTen.getText());
        vthang.setMaVe(nhapMaVeThang.getText());
        vthang.setMaXe(nhapMaXeThang.getText());
        vthang.setLoaiXe(LoaiXe3.getSelectedItem().toString());
        //kiểm tra ngoại lệ
        if(vthang.getHoTen().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập họ tên");
            
        }
        else if(vthang.getMaVe().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập mã vé");
        }
        else if(vthang.getMaVe().startsWith("VT") == FALSE)
        {
            JOptionPane.showMessageDialog(null,"Mã vé ngày phải bắt đầu bằng VT ");
        }
        else if(vthang.getMaXe().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập mã xe");
        }
        else{
        // ngày làm vé lấy ngày giờ hệ thống
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        // tạo 1 đối tượng có định dạng thời gian yyyy-MM-dd
        Date dateVao = new Date(); // lấy thời gian hệ thống
        String stringDate = dateFormat.format(dateVao);
        vthang.setNgayLam(stringDate);
        //ngày hết hạn
        String thoihan = thoiHan.getSelectedItem().toString();
        vthang.tinhThoiHan(vthang, dateVao, thoihan);
        noiVeThang.addVeThang(vthang);    
        }
    }//GEN-LAST:event_luuVeThangActionPerformed

    private void luuVeNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuVeNgayActionPerformed
        // TODO add your handling code here:
        VeNgay vngay  = new VeNgay();
        vngay.setMaVe(nhapMaVeNgay.getText());
        vngay.setMaXe(nhapMaXeNgay.getText());
        vngay.setLoaiXe(LoaiXe.getSelectedItem().toString());
        //kiểm tra ngoại lệ
        if(vngay.getMaVe().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập mã vé");
        }
        else if(vngay.getMaVe().startsWith("VN") == FALSE)
        {
            JOptionPane.showMessageDialog(null,"Mã vé ngày phải bắt đầu bằng VN ");
        }
        //kiểm tra mã vé đêm có trùng hay không
        else if(vngay.getMaXe().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập mã xe");
        }
        else{
        // ngày gửi lấy ngày giờ hệ thống
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        // tạo 1 đối tượng có định dạng thời gian yyyy-MM-dd
        Date date = new Date(); // lấy thời gian hệ thống
        String stringDate = dateFormat.format(date);
        vngay.setNgayGui(stringDate);
        noiVeNgay.addVeNgay(vngay);    
        }
    }//GEN-LAST:event_luuVeNgayActionPerformed

    private void kiemTraVeRaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiemTraVeRaActionPerformed
        // TODO add your handling code here:
        String mave = nhapMaVeRa.getText(); // lấy mã vé
        if(mave.length()==0)
        {
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập mã vé ra");
        }
        else if(mave.startsWith("VN") || mave.startsWith("vn")){               
            VeNgay vn = new VeNgay();
            if(noiVeNgay.KiemTraMV( mave))
            {
                KiemTraMaVe ktmv = new KiemTraMaVe();
                ktmv.setVisible(true); 
                noiVeNgay.TimVeNgay(vn, mave);
                ktmv.txtMaVe.setText(vn.getMaVe());
                ktmv.txtMaXe.setText(vn.getMaXe());
                ktmv.txtLoaiXe.setText(vn.getLoaiXe());
                ktmv.txtTGVao.setText(vn.getNgayGui());
                DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                // tạo 1 đối tượng có định dạng thời gian dd-MM-yyyy
                Date dateRa = new Date(); // lấy thời gian hệ thống
                String stringDateRa = dateFormat.format(dateRa);
                ktmv.txtTGRa.setText(stringDateRa);
                //tính số ngày xe gửi
                int sotien;
                sotien = vn.tinhTienVN(vn, vn.getNgayGui(), stringDateRa);
                ktmv.txtSoTien.setText(String.valueOf(sotien));
                ktmv.setVisible(true); 
            }
            else{
            JOptionPane.showMessageDialog(null,"Mã vé không tồn tại");
            }  
        }
        else if(mave.startsWith("VD") || mave.startsWith("vd")){
            VeDem vd = new VeDem();
            if(noiVeDem.KiemTraMV(mave))
            {
                KiemTraMaVe ktmv = new KiemTraMaVe();
                ktmv.setVisible(true);
                noiVeDem.TimVeDem(vd, mave);
                ktmv.txtMaVe.setText(vd.getMaVe());
                ktmv.txtMaXe.setText(vd.getMaXe());
                ktmv.txtLoaiXe.setText(vd.getLoaiXe());
                ktmv.txtTGVao.setText(vd.getNgayGui());
                DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                // tạo 1 đối tượng có định dạng thời gian dd-MM-yyyy
                Date dateRa = new Date(); // lấy thời gian hệ thống
                String stringDateRa = dateFormat.format(dateRa);
                ktmv.txtTGRa.setText(stringDateRa);
                //tính số ngày xe gửi
                int sotien;
                sotien = vd.tinhTienVD(vd, vd.getNgayGui(), stringDateRa);
                ktmv.txtSoTien.setText(String.valueOf(sotien));
                ktmv.setVisible(true); 
            }
            else{
            JOptionPane.showMessageDialog(null,"Mã vé không tồn tại");
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Mã vé không tồn tại");
        }
    }//GEN-LAST:event_kiemTraVeRaActionPerformed

    private void luuVeDemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuVeDemActionPerformed
        // TODO add your handling code here:
        VeDem vdem  = new VeDem();
        vdem.setMaVe(nhapMaVeDem.getText());
        vdem.setMaXe(nhapMaXeDem.getText());
        vdem.setLoaiXe(LoaiXe2.getSelectedItem().toString());
        //kiểm tra ngoại lệ
        if(vdem.getMaVe().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập mã vé");
        }
        else if(vdem.getMaVe().startsWith("VD") == FALSE)
        {
            JOptionPane.showMessageDialog(null,"Mã vé đêm phải bắt đầu bằng VD ");
        }
        //kiểm tra mã vé đêm có trùng hay không
        else if(vdem.getMaXe().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập mã xe");
        }
        else{
        // ngày gửi lấy ngày giờ hệ thống
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        // tạo 1 đối tượng có định dạng thời gian yyyy-MM-dd
        Date date = new Date(); // lấy thời gian hệ thống
        String stringDate = dateFormat.format(date);
        vdem.setNgayGui(stringDate);
        noiVeDem.addVeDem(vdem);    
        }
        
    }//GEN-LAST:event_luuVeDemActionPerformed

    private void nhapMaVeDemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapMaVeDemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhapMaVeDemActionPerformed

    private void thoiHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoiHanActionPerformed
        // TODO add your handling code here:
        String sothang = (String)thoiHan.getSelectedItem();
        int th = Integer.parseInt(sothang);
        int sotien;
        if(LoaiXe3.getSelectedItem().equals("Xe đạp")){
            sotien = th*70;
            GiaVe3.setText(sotien+".000 VND");
        }
        else if(LoaiXe3.getSelectedItem().equals("Xe máy")){
            sotien = th*100;
            GiaVe3.setText(sotien+".000 VND");
        }
    }//GEN-LAST:event_thoiHanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ThongTinVN ttvn = new ThongTinVN();
        ttvn.setVisible(true);
        ttvn.refreshTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ThongTinVD ttvd = new ThongTinVD();
        ttvd.setVisible(true);
        ttvd.refreshTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ThongTinVT ttvt = new ThongTinVT();
        ttvt.setVisible(true);
        ttvt.refreshTable();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void nhapMaXeThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapMaXeThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhapMaXeThangActionPerformed

    private void nutDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutDoanhThuActionPerformed
        // TODO add your handling code here:
        ThongTinDoanhThu ttdt = new ThongTinDoanhThu();
        ttdt.setVisible(true);
        ttdt.refreshTable();
    }//GEN-LAST:event_nutDoanhThuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        nhapMaVeNgay.setText("VN");
        nhapMaXeNgay.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        nhapMaVeDem.setText("VD");
        nhapMaXeDem.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        nhapHoTen.setText("VT");
        nhapMaVeThang.setText("");
        nhapMaXeThang.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiXe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GiaVe;
    private javax.swing.JLabel GiaVe2;
    private javax.swing.JLabel GiaVe3;
    private javax.swing.JComboBox<String> LoaiXe;
    private javax.swing.JComboBox<String> LoaiXe2;
    private javax.swing.JComboBox<String> LoaiXe3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton kiemTraVeRa;
    private javax.swing.JButton luuVeDem;
    private javax.swing.JButton luuVeNgay;
    private javax.swing.JButton luuVeThang;
    private javax.swing.JTextField nhapHoTen;
    private javax.swing.JTextField nhapMaVeDem;
    private javax.swing.JTextField nhapMaVeNgay;
    private javax.swing.JTextField nhapMaVeRa;
    private javax.swing.JTextField nhapMaVeThang;
    private javax.swing.JTextField nhapMaXeDem;
    private javax.swing.JTextField nhapMaXeNgay;
    private javax.swing.JTextField nhapMaXeThang;
    private javax.swing.JButton nutDoanhThu;
    private javax.swing.JComboBox thoiHan;
    // End of variables declaration//GEN-END:variables
}
